### ISSUE TITLE
Windows x64 MSVC Clang gnustep-2.0 -- Tests for NSURL* keep failing...

### ISSUE THREAD

**Issue by gcasa** [gnustep/libs-base#488]
Can we please correct the tests for this environment so that CI is not always RED?   Otherwise it looks like it is ALWAYS failing.

**Comment by triplef** [comment]
See https://github.com/gnustep/libs-base/issues/474#issuecomment-2602192093 for details.

**Comment by triplef** [comment]
@hmelder is it realistic to fix this in the short term, or should we just merge #478 to mark them as hopeful?

**Comment by gcasa** [comment]
```
  175 |                                                       [server port]]];
      |                                                       ^~~~~~~~~~~~~
15 warnings generated.
 Linking test_tool uploadTaskTests ...

base/NSURLSession/simpleTaskTests.m:
Failed file:  simpleTaskTests.m aborted without running all tests!
```
Is this test even compiling?

**Comment by hmelder** [comment]
Should be fixed now. Seems like something changed in the newer MSVC header files, so I needed to include `WS2tcpip.h` for `socklen_t`.

**Comment by triplef** [comment]
Unfortunately it looks like this test is still failing at least sometimes on Windows MSVC:
```
base/NSURLSession/simpleTaskTests.m:
Failed test:     (2025-02-06 19:52:45.095 +0000) simpleTaskTests.m:875 ... All transfers were completed before a timeout occurred
```

**Comment by hmelder** [comment]
Ah yes that seems to be a sporadic failure due to libdispatch https://github.com/swiftlang/swift-corelibs-libdispatch/issues/833

**Comment by rfm** [comment]
A key feature of GNUstep is its support for writing highly portable app, so we should not have a dependency on libdispatch.
The first step to a fix would be to remove that dependency, and the second would be to conditionally allow its use for platforms/versions which are known to be working.  I don't recall whether the previous NSURLSession implementation had the same problem; perhaps we should revert to it?

**Comment by rfm** [comment]
The older implementation is just as bad in using libdispatch, so there's no quick fix  :-(

**Comment by hmelder** [comment]
> I don't recall whether the previous NSURLSession implementation had the same problem; perhaps we should revert to it?

The old one is completely broken
